# Generated by Django 3.0.8 on 2020-08-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
