# Generated by Django 3.0.8 on 2020-09-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_people_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='passwd',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
