# Generated by Django 3.0.8 on 2021-03-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_people_passwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='dob',
        ),
    ]
