# Generated by Django 3.0.8 on 2021-03-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_people_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='state',
            field=models.CharField(default='Happy', max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='lname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='passwd',
            field=models.CharField(max_length=100),
        ),
    ]
