# Generated by Django 3.0.8 on 2021-03-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_people_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='bio',
            field=models.TextField(default='Hello There'),
        ),
    ]
